services:
  mbti_db:
    build:
      context: .
      dockerfile: Dockerfile.db
    image: sareer/mbti-db:latest
    container_name: mbti_db
    networks:
      - mbti_net
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot_password" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  mbti_portal:
    build:
      context: .
      dockerfile: Dockerfile
    image: sareer/mbti-portal:latest
    container_name: mbti_portal
    depends_on:
      mbti_db:
        condition: service_healthy
    networks:
      - mbti_net
    ports:
      - "80:80"
      - "389:389"
      - "2049:2049"
      - "111:111"
    volumes:
      - nfs_share:/var/nfs/internal
      - ./portal:/var/www/portal
      - ./www:/var/www/html
    restart: unless-stopped
    privileged: true
    cap_add:
      - SYS_ADMIN

networks:
  mbti_net:
    driver: bridge

volumes:
  nfs_share:
